<a href="https://colab.research.google.com/github/hoanganhloan172/Data_analys_with_python/blob/main/Buoi_6/BAitap6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import numpy as np

A = np.array([[10,1,2],
              [9,7,4],
              [0,2,1]])
B =np.array([[2,3,4],
             [0,4,2],
             [3,2,1]])

#AB
tich = np.dot(A,B)
tich

array([[26, 38, 44],
       [30, 63, 54],
       [ 3, 10,  5]])

In [ ]:

# Tính B * A^T * A * B^T
result1 = np.dot(B, np.dot(A.T, np.dot(A, B.T)))

# Tính A * B^T * B * A^T
result2 = np.dot(A, np.dot(B.T, np.dot(B, A.T)))

print("B * A^T * A * B^T:")
print(result1)

print("\nA * B^T * B * A^T:")
print(result2)

B * A^T * A * B^T:
[[4086 2328 3579]
 [2328 1460 1942]
 [3579 1942 3206]]

A * B^T * B * A^T:
[[2181 3523  560]
 [3523 6346 1135]
 [ 560 1135  225]]


In [ ]:
# Concatenate ma trận A và B theo dòng
concatenated_matrix = np.concatenate((A, B), axis=0)

# Reshape ma trận A thành vecto
reshaped_vector = A.reshape(-1)

print("Concatenated Matrix A and B:")
print(concatenated_matrix)

print("\nReshaped Vector from Matrix A:")
print(reshaped_vector)

Concatenated Matrix A and B:
[[10  1  2]
 [ 9  7  4]
 [ 0  2  1]
 [ 2  3  4]
 [ 0  4  2]
 [ 3  2  1]]

Reshaped Vector from Matrix A:
[10  1  2  9  7  4  0  2  1]


In [ ]:
A = np.array([[10,1,2],
              [9,7,4],
              [0,2,1]])
def softmax(x):
    exp_x = np.exp(x - np.max(x, axis=-1, keepdims=True))
    return exp_x / np.sum(exp_x, axis=-1, keepdims=True)

# Tính phân phối xác suất sau khi đi qua hàm softmax cho mỗi dòng
softmax_result = softmax(A)

# Tìm nhãn dự báo cho mỗi dòng
predicted_labels = np.argmax(softmax_result, axis=1)

# Tính tổng, trung bình, min và max của mỗi dòng
sums = np.sum(A, axis=1)
means = np.mean(A, axis=1)
mins = np.min(A, axis=1)
maxs = np.max(A, axis=1)

print("Phân phối xác suất sau softmax:")
print(softmax_result)

print("\nNhãn dự báo cho mỗi dòng:")
print(predicted_labels)

print("\nTổng của mỗi dòng:")
print(sums)

print("\nTrung bình của mỗi dòng:")
print(means)

print("\nMin của mỗi dòng:")
print(mins)

print("\nMax của mỗi dòng:")
print(maxs)


Phân phối xác suất sau softmax:
[[9.99541338e-01 1.23353201e-04 3.35308764e-04]
 [8.75600595e-01 1.18499655e-01 5.89975040e-03]
 [9.00305732e-02 6.65240956e-01 2.44728471e-01]]

Nhãn dự báo cho mỗi dòng:
[0 0 1]

Tổng của mỗi dòng:
[13 20  3]

Trung bình của mỗi dòng:
[4.33333333 6.66666667 1.        ]

Min của mỗi dòng:
[1 4 0]

Max của mỗi dòng:
[10  9  2]


In [ ]:

#bai tap voi file excel
import numpy as np
import pandas as pd
dataset = pd.read_excel("/content/Week4-data_06 (1).xlsx")
print(dataset)
print(dataset.head())

                     Tên  Mã số               Trường cấp 2  Nguyện vọng 1  \
0           QUÁCH KIM HÀ  60132             THCS Phú Cường              6   
1       PHẠM TRÚC PHƯƠNG  60421        THCS Trần Đại Nghĩa              6   
2         TRẦN KHẢ DOANH  60075    THCS-THPT Nguyễn Khuyến              6   
3      NGUYỄN MAI PHƯƠNG  60417        THCS Trần Đại Nghĩa              6   
4          TRẦN MINH THY  60558  THCS Nguyễn Thị Minh Khai              6   
..                   ...    ...                        ...            ...   
636        TRẦN NHẬT ANH  60032       THCS Nguyễn Văn Tiết              6   
637  DOÃN THỊ PHƯƠNG ANH  60017            THCS Bình Chiểu              6   
638       CÙ THỊ GIA HÂN  60151     THCS Nguyễn Trung Trực              6   
639      NGUYỄN TƯỜNG VY  60622        THCS Trịnh Hoài Đức              6   
640         LƯU QUANG ĐÔ  60108        THCS Trịnh Hoài Đức              6   

     Nguyện vọng 2  Điểm cộng   Văn   Anh  Toán   Tổng  Xếp hạng  
0       

In [ ]:

data = dataset.to_numpy()
print(data.shape)

(641, 11)


In [ ]:

print(data[0])

['QUÁCH KIM HÀ' 60132 'THCS Phú Cường' 6 2.0 3.0 9.0 8.9 8.75 29.65 1]


In [ ]:


print(data.dtype)


object


In [ ]:

print(data[0].dtype)

object


In [ ]:

np.nan_to_num([0.3, np.nan, 2.4])

array([0.3, 0. , 2.4])

In [ ]:


data[:, 5] = np.nan_to_num(data[:, 5].astype(float))
print(data[:, 5])
print(data[-1])

[3.0 2.0 2.0 0.0 2.0 0.0 2.0 0.0 0.0 2.0 2.0 0.0 1.0 0.0 0.0 2.0 2.0 1.0
 0.0 1.0 0.0 0.0 0.0 0.0 2.0 2.0 2.0 0.0 2.0 0.0 0.0 2.0 0.0 0.0 0.0 0.0
 0.0 0.0 0.0 0.0 2.0 0.0 2.0 0.0 2.0 0.0 2.5 0.0 0.0 0.0 2.0 0.0 0.0 0.0
 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
 1.0 0.0 2.0 0.0 1.0 0.0 1.0 2.0 0.0 0.0 0.0 0.0 0.0 2.0 0.0 2.0 1.0 0.0
 1.0 0.0 1.0 0.0 1.0 0.0 0.0 1.0 0.0 1.0 2.0 0.0 0.0 0.0 0.0 0.0 2.0 0.0
 0.0 1.0 0.0 0.0 0.0 0.0 1.0 1.0 1.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 2.0 0.0
 0.0 2.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0
 0.0 1.0 0.0 2.0 0.0 0.0 0.0 2.0 2.0 1.0 1.0 0.0 0.0 0.0 0.0 2.0 0.0 0.0
 1.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 2.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0
 2.0 0.0 2.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0
 0.0 0.0 0.0 1.0 2.0 0.0 0.0 0.0 0.0 2.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0
 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0
 1.0 1.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.

In [ ]:

## Đưa ra thông tin của bạn với mã số: 60457
info_60457 = dataset[dataset['Mã số'] == 60457]
print("Thông tin với mã số 60457:")
print(info_60457)

Thông tin với mã số 60457:
                      Tên  Mã số   Trường cấp 2  Nguyện vọng 1  Nguyện vọng 2  \
100  NGUYỄN LÊ PHƯƠNG TÂM  60457  THCS Phú Long              6            7.0   

     Điểm cộng  Văn  Anh  Toán   Tổng  Xếp hạng  
100        2.0  7.0  9.4  6.25  24.65       101  


In [ ]:

## Đưa ra thông tin của bạn với tên là: Nguyễn Đình Nhân
info_name = dataset[dataset['Tên'] ==  'Nguyễn Đình Nhân']
print("Thông tin của bạn Nguyễn Đình Nhân:")
print(info_name)

Thông tin của bạn Nguyễn Đình Nhân:
Empty DataFrame
Columns: [Tên, Mã số, Trường cấp 2, Nguyện vọng 1, Nguyện vọng 2, Điểm cộng, Văn, Anh, Toán, Tổng, Xếp hạng]
Index: []


In [ ]:
## Đưa ra thông tin của các bạn từ mã số: 60004 đến  60200 (Bạn nào không có thì không cần đưa ra)
info_60004_60200 = dataset[(dataset['Mã số'] >= 60004) & (dataset['Mã số'] <= 60200)]

# Hiển thị thông tin
print("Thông tin của các bạn từ mã số 60004 đến 60200:")
print(info_60004_60200)

Thông tin của các bạn từ mã số 60004 đến 60200:
                     Tên  Mã số               Trường cấp 2  Nguyện vọng 1  \
0           QUÁCH KIM HÀ  60132             THCS Phú Cường              6   
2         TRẦN KHẢ DOANH  60075    THCS-THPT Nguyễn Khuyến              6   
5     PHẠM LỢI NGỌC HIỀN  60158         THCS Châu Văn Liêm              6   
7         ĐẶNG MINH CHÂU  60067  THCS Nguyễn Thị Minh Khai              6   
10         NGÔ MỸ GIA AN  60004    THCS-THPT Nguyễn Khuyến              6   
..                   ...    ...                        ...            ...   
634      NGUYỄN TUẤN ANH  60033            THCS Thanh Bình              6   
636        TRẦN NHẬT ANH  60032       THCS Nguyễn Văn Tiết              6   
637  DOÃN THỊ PHƯƠNG ANH  60017            THCS Bình Chiểu              6   
638       CÙ THỊ GIA HÂN  60151     THCS Nguyễn Trung Trực              6   
640         LƯU QUANG ĐÔ  60108        THCS Trịnh Hoài Đức              6   

     Nguyện vọng 2  Điểm cộ

In [ ]:

# Tính điểm trung bình cho từng sinh viên
dataset['Điểm Trung Bình'] = dataset[['Văn', 'Anh', 'Toán']].mean(axis=1)

# Hiển thị thông tin với cột Điểm Trung Bình mới thêm vào
print("Thông tin với điểm trung bình:")
print(dataset[['Mã số', 'Tên', 'Văn', 'Anh', 'Toán', 'Điểm Trung Bình']])

Thông tin với điểm trung bình:
     Mã số                  Tên   Văn   Anh  Toán  Điểm Trung Bình
0    60132         QUÁCH KIM HÀ  9.00   8.9  8.75         8.883333
1    60421     PHẠM TRÚC PHƯƠNG  8.75   9.6  9.25         9.200000
2    60075       TRẦN KHẢ DOANH  8.25   9.6  9.25         9.033333
3    60417    NGUYỄN MAI PHƯƠNG  8.75  10.0  9.25         9.333333
4    60558        TRẦN MINH THY  8.25   9.7  8.00         8.650000
..     ...                  ...   ...   ...   ...              ...
636  60032        TRẦN NHẬT ANH  6.75   3.9  2.75         4.466667
637  60017  DOÃN THỊ PHƯƠNG ANH  6.25   3.6  3.50         4.450000
638  60151       CÙ THỊ GIA HÂN  6.00   3.5  3.25         4.250000
639  60622      NGUYỄN TƯỜNG VY  6.25   3.2  3.00         4.150000
640  60108         LƯU QUANG ĐÔ  5.50   2.4  3.75         3.883333

[641 rows x 6 columns]


In [ ]:

# Tính điểm trung bình theo từng môn
diemTB_van = dataset['Văn'].mean()
diemTB_anh = dataset['Anh'].mean()
diemTB_toan = dataset['Toán'].mean()

# Hiển thị thông tin
print("Điểm trung bình theo từng môn:")
print("Điểm Trung Bình Văn:", diemTB_van)
print("Điểm Trung Bình Anh:", diemTB_anh)
print("Điểm Trung Bình Toán:", diemTB_toan)

Điểm trung bình theo từng môn:
Điểm Trung Bình Văn: 7.287051482059282
Điểm Trung Bình Anh: 6.99625585023401
Điểm Trung Bình Toán: 7.1080343213728545


In [ ]:
## Đưa ra điểm thi trung bình cao nhất và thấp nhất cho toàn bộ 3 môn.
max_tong = max(diemTB_van, diemTB_anh, diemTB_toan)
min_tong = min(diemTB_van, diemTB_anh, diemTB_toan)

# Hiển thị thông tin
print("Điểm Trung Bình Cao Nhất:", max_tong)
print("Điểm Trung Bình Thấp Nhất:", min_tong)


Điểm Trung Bình Cao Nhất: 7.287051482059282
Điểm Trung Bình Thấp Nhất: 6.99625585023401


In [ ]:

## Xếp danh sách dựa vào điểm trung bình của môn Toán + Anh, tìm bạn có vị trí 100
# Tính điểm trung bình của môn Toán + Anh
dataset['Điểm Trung Bình Toán Anh'] = dataset[['Anh', 'Toán']].mean(axis=1)

# Xếp danh sách theo điểm trung bình Toán + Anh
dataset_sorted = dataset.sort_values(by='Điểm Trung Bình Toán Anh', ascending=False)

# Hiển thị thông tin
print("Danh sách xếp hạng theo điểm trung bình Toán + Anh:")
print(dataset_sorted[['Mã số', 'Tên', 'Điểm Trung Bình Toán Anh']])

# Tìm bạn có vị trí 100
student_at_rank_100 = dataset_sorted.iloc[99] if len(dataset_sorted) >= 100 else None

# Hiển thị thông tin về bạn có vị trí 100
if student_at_rank_100 is not None:
    print("\nThông tin của bạn có vị trí 100:")
    print(student_at_rank_100)
else:
    print("\nKhông có đủ sinh viên để đạt đến vị trí 100.")

Danh sách xếp hạng theo điểm trung bình Toán + Anh:
     Mã số                  Tên  Điểm Trung Bình Toán Anh
11   60169       NGUYỄN AN HOÀI                     9.750
5    60158   PHẠM LỢI NGỌC HIỀN                     9.700
3    60417    NGUYỄN MAI PHƯƠNG                     9.625
8    60334         LÊ MINH NGỌC                     9.525
23   60129        PHẠM THANH HÀ                     9.500
..     ...                  ...                       ...
637  60017  DOÃN THỊ PHƯƠNG ANH                     3.550
638  60151       CÙ THỊ GIA HÂN                     3.375
636  60032        TRẦN NHẬT ANH                     3.325
639  60622      NGUYỄN TƯỜNG VY                     3.100
640  60108         LƯU QUANG ĐÔ                     3.075

[641 rows x 3 columns]

Thông tin của bạn có vị trí 100:
Tên                         NGUYỄN NGỌC QUỲNH ANH
Mã số                                       60010
Trường cấp 2                  THCS Trịnh Hoài Đức
Nguyện vọng 1                               

In [ ]:


## Giả sử 1 trường lấy toàn bộ 300 sinh viên, dựa theo
## a) Điểm môn Toán từ cao xuống thấp
## b) Điểm tổng 3 môn và điểm cộng từ cao xuống thấp
## c) Điểm trung bình 3 môn từ cao xuống thấp
## Đưa ra danh sách những bạn sinh viên được chọn vào trường đó.

# a) Sắp xếp theo điểm môn Toán từ cao xuống thấp
toan_sorted = dataset.sort_values(by='Toán', ascending=False)

# Lấy 300 sinh viên đầu tiên
selected_students_toan = toan_sorted.head(300)

# Hiển thị thông tin
print("Danh sách sinh viên được chọn dựa trên điểm môn Toán:")
print(selected_students_toan)

Danh sách sinh viên được chọn dựa trên điểm môn Toán:
                            Tên  Mã số               Trường cấp 2  \
8                  LÊ MINH NGỌC  60334        THCS Trần Đại Nghĩa   
23                PHẠM THANH HÀ  60129  THCS Nguyễn Thị Minh Khai   
20                  LƯU MINH ÂN  60037        THCS Trần Đại Nghĩa   
5            PHẠM LỢI NGỌC HIỀN  60158         THCS Châu Văn Liêm   
11               NGUYỄN AN HOÀI  60169    THCS-THPT Nguyễn Khuyến   
..                          ...    ...                        ...   
346    NGUYỄN HUYỀN PHƯƠNG THẢO  60504          THCS Bình Thắng B   
166         BÙI MINH KHÁNH ĐOAN  60107            THCS Chu Văn An   
189  NGUYỄN TRƯỜNG THỤY ANH THƯ  60541        THCS Trịnh Hoài Đức   
162            PHẠM PHƯƠNG ĐÔNG  60109       THCS Nguyễn Văn Tiết   
342              MAI THANH BÌNH  60055        THCS Trịnh Hoài Đức   

     Nguyện vọng 1  Nguyện vọng 2  Điểm cộng   Văn   Anh  Toán   Tổng  \
8                6            7.0        NaN

In [ ]:


## Giả sử 1 trường lấy toàn bộ 300 sinh viên, dựa theo
## a) Điểm môn Toán từ cao xuống thấp
## b) Điểm tổng 3 môn và điểm cộng từ cao xuống thấp
## c) Điểm trung bình 3 môn từ cao xuống thấp
## Đưa ra danh sách những bạn sinh viên được chọn vào trường đó.

# a) Sắp xếp theo điểm môn Toán từ cao xuống thấp
toan_sorted = dataset.sort_values(by='Toán', ascending=False)

# Lấy 300 sinh viên đầu tiên
selected_students_toan = toan_sorted.head(300)

# Hiển thị thông tin
print("Danh sách sinh viên được chọn dựa trên điểm môn Toán:")
print(selected_students_toan)

Danh sách sinh viên được chọn dựa trên điểm môn Toán:
                            Tên  Mã số               Trường cấp 2  \
8                  LÊ MINH NGỌC  60334        THCS Trần Đại Nghĩa   
23                PHẠM THANH HÀ  60129  THCS Nguyễn Thị Minh Khai   
20                  LƯU MINH ÂN  60037        THCS Trần Đại Nghĩa   
5            PHẠM LỢI NGỌC HIỀN  60158         THCS Châu Văn Liêm   
11               NGUYỄN AN HOÀI  60169    THCS-THPT Nguyễn Khuyến   
..                          ...    ...                        ...   
346    NGUYỄN HUYỀN PHƯƠNG THẢO  60504          THCS Bình Thắng B   
166         BÙI MINH KHÁNH ĐOAN  60107            THCS Chu Văn An   
189  NGUYỄN TRƯỜNG THỤY ANH THƯ  60541        THCS Trịnh Hoài Đức   
162            PHẠM PHƯƠNG ĐÔNG  60109       THCS Nguyễn Văn Tiết   
342              MAI THANH BÌNH  60055        THCS Trịnh Hoài Đức   

     Nguyện vọng 1  Nguyện vọng 2  Điểm cộng   Văn   Anh  Toán   Tổng  \
8                6            7.0        NaN

In [ ]:

# c) Sắp xếp theo điểm trung bình 3 môn từ cao xuống thấp
trung_binh_sorted = dataset.sort_values(by='Điểm Trung Bình', ascending=False)

# Lấy 300 sinh viên đầu tiên
selected_students_trung_binh = trung_binh_sorted.head(300)
print("\nDanh sách sinh viên được chọn dựa trên điểm trung bình 3 môn:")
print(selected_students_trung_binh)



Danh sách sinh viên được chọn dựa trên điểm trung bình 3 môn:
                      Tên  Mã số               Trường cấp 2  Nguyện vọng 1  \
3       NGUYỄN MAI PHƯƠNG  60417        THCS Trần Đại Nghĩa              6   
5      PHẠM LỢI NGỌC HIỀN  60158         THCS Châu Văn Liêm              6   
7          ĐẶNG MINH CHÂU  60067  THCS Nguyễn Thị Minh Khai              6   
8            LÊ MINH NGỌC  60334        THCS Trần Đại Nghĩa              6   
1        PHẠM TRÚC PHƯƠNG  60421        THCS Trần Đại Nghĩa              6   
..                    ...    ...                        ...            ...   
316     VŨ TRỊNH LINH NHI  60352              THCS Phú Long              6   
152      NGUYỄN THÁI LONG  60268              THCS Phú Long              6   
151  NGUYỄN THỊ THÙY TRÂM  60575        THCS Trịnh Hoài Đức              6   
317  NGUYỄN TRẦN HOÀNG VI  60603        THCS Trần Đại Nghĩa              6   
318    TRẦN TÔ THANH LIÊM  60245        THCS Trịnh Hoài Đức              6   



## So sánh 2 bạn sinh viên mã số: 60575 và 60602 dựa trên tổng điểm 3 môn (không tính điểm cộng)


In [ ]:
dataset.head()

student_1 = dataset.loc[dataset['Mã số'] == 60575]
student_2 = dataset.loc[dataset['Mã số'] == 60602]

print(student_1['Văn'])
print(student_1['Toán'])
print(student_1['Anh'])



151    5.75
Name: Văn, dtype: float64
151    7.5
Name: Toán, dtype: float64
151    8.6
Name: Anh, dtype: float64


In [ ]:
student_1.values[0][0]

'NGUYỄN THỊ THÙY TRÂM'

In [ ]:
#tính điểm cho sinh viên thứ nhất
total1 = student_1['Văn']+student_1['Toán']+student_1['Anh']
total1

151    21.85
dtype: float64

In [ ]:
#tính tổng điểm của sinh viên thứ 2
total2 = student_2['Văn']+student_2['Toán']+student_2['Anh']
total2

191    23.3
dtype: float64

In [ ]:
if total1.values[0] > total2.values[0]:
  print('sinh viên có mã số 60575 có tổng điểm cao hơn')
else:
  print('sinh viên có mã số 60575 có tổng điểm thấp hơn')

21.85